"""Backward-compatible imports for Phillip's paper-conversion contracts."""

from protofuse.phillip.contracts import (
    ComponentBinding,
    ComponentSpec,
    ConstraintSpec,
    ContractModel,
    Evidence,
    ExecutionDevice,
    ExperimentalMeasurement,
    GeneratorSpec,
    MethodologySpec,
    ModelDependency,
    OptimizerSpec,
    PaperRef,
    ProtoPlan,
    SelectionThreshold,
    TopologyKind,
    TopologyRecommendation,
    WorkflowEdge,
    WorkflowStep,
    WorkflowTopology,
)

__all__ = [
    "ComponentBinding",
    "ComponentSpec",
    "ConstraintSpec",
    "ContractModel",
    "Evidence",
    "ExecutionDevice",
    "ExperimentalMeasurement",
    "GeneratorSpec",
    "MethodologySpec",
    "ModelDependency",
    "OptimizerSpec",
    "PaperRef",
    "ProtoPlan",
    "SelectionThreshold",
    "TopologyKind",
    "TopologyRecommendation",
    "WorkflowEdge",
    "WorkflowStep",
    "WorkflowTopology",
]
